import type { InquiryComment } from '@/shared/types';

export const INQUIRY_COMMENT_MOCK_DATA: Record<number, InquiryComment[]> = {
  12: [
    {
      id: 1200,
      postId: 12,
      userId: '23123456',
      userRoleId: 2,
      userDisplay: '숙명이',
      isWriter: false,
      isWriterWithdrawn: false,
      content: '혹시 발표 일정이 언제로 변경되었는지 알 수 있을까요?',
      createdAt: '2026-04-12T15:30:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: false,
      children: [
        {
          id: 1202,
          postId: 12,
          userId: 'admin02',
          userRoleId: 5,
          userDisplay: 'admin02',
          isWriter: true,
          isWriterWithdrawn: false,
          content: '발표 일정은 이번 주 금요일로 변경되었습니다.',
          createdAt: '2026-04-12T15:45:00.000000',
          updatedAt: null,
          isVisible: true,
          isUpdated: false,
          isDeleted: false,
          children: [],
        },
      ],
    },
    {
      id: 1201,
      postId: 12,
      userId: 'admin02',
      userRoleId: 5,
      userDisplay: 'admin02',
      isWriter: true,
      isWriterWithdrawn: false,
      content:
        '이벤트 당첨자 발표 일정이 변경되어 공지에 반영했습니다. 확인 부탁드립니다.',
      createdAt: '2026-04-12T16:10:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: false,
      children: [],
    },
  ],
  15: [
    {
      id: 1501,
      postId: 15,
      userId: 'admin01',
      userRoleId: 5,
      userDisplay: 'admin01',
      isWriter: true,
      isWriterWithdrawn: false,
      content: '신고된 댓글을 확인했습니다.',
      createdAt: '2026-04-09T14:20:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: false,
      children: [
        {
          id: 1503,
          postId: 15,
          userId: '24123456',
          userRoleId: 2,
          userDisplay: '댓글러',
          isWriter: false,
          isWriterWithdrawn: false,
          content: '확인 감사합니다. 처리 결과도 알려주세요.',
          createdAt: '2026-04-09T14:42:00.000000',
          updatedAt: null,
          isVisible: true,
          isUpdated: false,
          isDeleted: false,
          children: [],
        },
      ],
    },
    {
      id: 1502,
      postId: 15,
      userId: 'admin02',
      userRoleId: 5,
      userDisplay: 'admin02',
      isWriter: true,
      isWriterWithdrawn: false,
      content: '해당 댓글은 정책 위반으로 삭제 처리했습니다.',
      createdAt: '2026-04-09T15:05:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: false,
      children: [],
    },
  ],
  19: [
    {
      id: 1901,
      postId: 19,
      userId: 'admin01',
      userRoleId: 5,
      userDisplay: 'admin01',
      isWriter: true,
      isWriterWithdrawn: false,
      content: '광고성 게시글로 판단되어 비공개 처리했습니다.',
      createdAt: '2026-04-05T13:30:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: false,
      children: [],
    },
  ],
  22: [
    {
      id: 2201,
      postId: 22,
      userId: 'admin02',
      userRoleId: 5,
      userDisplay: 'admin02',
      isWriter: true,
      isWriterWithdrawn: false,
      content: '',
      createdAt: '2026-04-02T18:25:00.000000',
      updatedAt: null,
      isVisible: true,
      isUpdated: false,
      isDeleted: true,
      children: [
        {
          id: 2202,
          postId: 22,
          userId: '24242424',
          userRoleId: 2,
          userDisplay: '알림확인',
          isWriter: false,
          isWriterWithdrawn: false,
          content: '대댓글은 그대로 보여야 합니다.',
          createdAt: '2026-04-02T18:40:00.000000',
          updatedAt: null,
          isVisible: true,
          isUpdated: false,
          isDeleted: false,
          children: [],
        },
      ],
    },
  ],
};
