import type { InquiryDetail } from '@/shared/types';

const INQUIRY_TARGET_BASE_URL =
  'https://feature-support.snorose-front-react.pages.dev';

const getInquiryTargetLink = (postId: number) =>
  `${INQUIRY_TARGET_BASE_URL}/report/${postId}`;

export const INQUIRY_DETAIL_MOCK_DATA: Record<number, InquiryDetail> = {
  11: {
    postId: 11,
    userRoleId: 3,
    isWriter: false,
    userId: 12345678,
    userDisplay: '눈송',
    title: '시험후기 신고합니다',
    content:
      '해당 시험후기는 실제 시험 내용과 전혀 관련 없는 허위 정보를 담고 있습니다. 작성자가 시험을 실제로 응시하지 않은 것으로 보이며, 내용이 불성실하고 다른 사용자에게 혼란을 줄 수 있어 신고합니다. 빠른 조치 부탁드립니다.',
    reportCause: 'EXAM_FALSE_REVIEW',
    target: '101',
    link: getInquiryTargetLink(11),
    group: 'REPORT',
    subGroup: 'EXAM_REVIEW_REPORT',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-13T22:30:11.519393',
    updatedAt: '2026-04-14T10:05:22.000000',
    isEdited: true,
    isWriterWithdrawn: false,
    attachments: [],
  },
  12: {
    postId: 12,
    userRoleId: 2,
    isWriter: false,
    userId: 23123456,
    userDisplay: '숙명이',
    title: '이벤트 당첨자 발표 관련 문의드립니다',
    content:
      '이번 봄맞이 이벤트 당첨자 발표가 공지된 날짜보다 늦어지고 있어 문의드립니다. 이벤트 참여 후 결과를 기다리고 있었는데 아직 발표가 없어 걱정됩니다. 발표 일정이 변경된 경우 알림을 주시면 감사하겠습니다.',
    reportCause: null,
    target: null,
    link: getInquiryTargetLink(12),
    group: 'INQUIRY',
    subGroup: 'EVENT_INQUIRY',
    status: 'COMPLETED',
    commentCount: 1,
    createdAt: '2026-04-12T14:21:03.123456',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
  13: {
    postId: 13,
    userRoleId: 2,
    isWriter: false,
    userId: 22111111,
    userDisplay: '설화',
    title: '게시글에 개인정보가 포함되어 있어요',
    content:
      '해당 게시글에 특정 학생의 이름, 학번, 연락처가 동의 없이 노출되어 있습니다. 개인정보보호법 위반에 해당할 수 있으므로 즉각적인 삭제 조치가 필요합니다. 관련 캡처 이미지도 첨부하였으니 확인 부탁드립니다.',
    reportCause: 'POST_PERSONAL_DATA_LEAK',
    target: '205',
    link: getInquiryTargetLink(13),
    group: 'REPORT',
    subGroup: 'POST_REPORT',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-11T09:12:45.000000',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [
      {
        id: 1,
        url: 'https://snorose-bucket.s3.ap-northeast-2.amazonaws.com/mock/screenshot1.jpg',
        type: 'PHOTO',
        fileName: 'screenshot1.jpg',
        fileComment: '개인정보 노출 캡처',
      },
    ],
  },
  14: {
    postId: 14,
    userRoleId: 2,
    isWriter: false,
    userId: 20123456,
    userDisplay: '공지맨',
    title: '공지 내용이 잘못 표시됩니다',
    content:
      '앱 공지 화면에서 날짜 정보가 잘못 표기되고 있습니다. 실제 행사 날짜는 4월 20일인데 공지에는 4월 10일로 표시되어 있어 혼란이 생길 수 있습니다. 또한 일부 특수문자가 깨져서 보이는 현상도 확인하였으니 수정 부탁드립니다.',
    reportCause: null,
    target: null,
    link: getInquiryTargetLink(14),
    group: 'INQUIRY',
    subGroup: 'NOTICE_INQUIRY',
    status: 'HOLD',
    commentCount: 0,
    createdAt: '2026-04-10T18:44:20.456789',
    updatedAt: '2026-04-11T08:30:00.000000',
    isEdited: true,
    isWriterWithdrawn: false,
    attachments: [],
  },
  15: {
    postId: 15,
    userRoleId: 2,
    isWriter: false,
    userId: 24123456,
    userDisplay: '댓글러',
    title: '댓글 신고합니다',
    content:
      '해당 게시글의 댓글에 특정 사용자를 향한 욕설과 심각한 인신공격성 발언이 포함되어 있습니다. 다른 사용자들이 불쾌감을 느낄 수 있으며, 커뮤니티 규정에도 명백히 위반됩니다. 해당 댓글 삭제 및 작성자 제재를 요청합니다.',
    reportCause: 'COMMENT_INSULT_OR_DEFAMATION',
    target: '318',
    link: getInquiryTargetLink(15),
    group: 'REPORT',
    subGroup: 'COMMENT_REPORT',
    status: 'COMPLETED',
    commentCount: 2,
    createdAt: '2026-04-09T13:08:37.111111',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [
      {
        id: 2,
        url: 'https://snorose-bucket.s3.ap-northeast-2.amazonaws.com/mock/comment_screenshot.jpg',
        type: 'PHOTO',
        fileName: 'comment_screenshot.jpg',
        fileComment: '욕설 댓글 캡처',
      },
    ],
  },
  16: {
    postId: 16,
    userRoleId: 2,
    isWriter: false,
    userId: 19123456,
    userDisplay: '족보왕',
    title: '족보 업로드 기준 문의',
    content:
      '족보를 업로드하려고 하는데 어떤 형식과 기준에 맞춰야 하는지 궁금합니다. 특히 PDF 파일 크기 제한, 허용되는 과목 범위, 그리고 저작권 관련 주의사항이 있다면 안내해 주시면 감사하겠습니다. 처음 업로드하는 거라 자세한 가이드라인이 필요합니다.',
    reportCause: null,
    target: null,
    link: getInquiryTargetLink(16),
    group: 'INQUIRY',
    subGroup: 'EXAM_REVIEW_INQUIRY',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-08T10:30:00.000000',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
  17: {
    postId: 17,
    userRoleId: 2,
    isWriter: false,
    userId: 25111111,
    userDisplay: '신고자',
    title: '외부인으로 의심되는 유저가 있습니다',
    content:
      '해당 유저가 재학생 인증 없이 커뮤니티에 접근하고 있는 것으로 의심됩니다. 게시글 작성 패턴과 내용을 보면 외부인일 가능성이 높으며, 내부 정보를 외부로 유출하려는 시도가 보입니다. 해당 계정에 대한 인증 여부 확인 및 조치를 요청드립니다.',
    reportCause: 'USER_OUTSIDER',
    target: '9981',
    link: getInquiryTargetLink(17),
    group: 'REPORT',
    subGroup: 'USER_REPORT',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-07T21:19:54.333333',
    updatedAt: '2026-04-08T09:00:00.000000',
    isEdited: true,
    isWriterWithdrawn: false,
    attachments: [],
  },
  18: {
    postId: 18,
    userRoleId: 2,
    isWriter: false,
    userId: 22222222,
    userDisplay: '기타맨',
    title: '기타 문의 사항입니다',
    content:
      '앱을 사용하다가 발견한 기타 불편 사항을 문의드립니다. 알림 설정을 변경해도 저장이 되지 않는 오류가 있으며, 로그아웃 후 재로그인 시 이전 설정값이 초기화되는 문제도 경험했습니다. 해당 문제를 확인하고 수정해 주시면 감사하겠습니다.',
    reportCause: null,
    target: null,
    link: getInquiryTargetLink(18),
    group: 'ETC',
    subGroup: 'ETC_INQUIRY',
    status: 'HOLD',
    commentCount: 0,
    createdAt: '2026-04-06T16:02:10.999999',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
  19: {
    postId: 19,
    userRoleId: 2,
    isWriter: false,
    userId: 20202020,
    userDisplay: '깨끗한보드',
    title: '상업적 광고 게시글 신고',
    content:
      '해당 게시글은 특정 학원 및 과외 서비스를 홍보하는 상업적 광고 내용으로 구성되어 있습니다. 커뮤니티 이용 규정상 영리 목적의 광고 게시는 금지되어 있으며, 동일 계정에서 반복적으로 비슷한 게시글을 작성하고 있어 신고합니다.',
    reportCause: 'POST_COMMERCIAL_ADVERTISEMENT',
    target: '441',
    link: getInquiryTargetLink(19),
    group: 'REPORT',
    subGroup: 'POST_REPORT',
    status: 'COMPLETED',
    commentCount: 1,
    createdAt: '2026-04-05T11:55:42.777777',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
  20: {
    postId: 20,
    userRoleId: 2,
    isWriter: false,
    userId: 21212121,
    userDisplay: '족보체크',
    title: '허위 족보로 보여 신고합니다',
    content:
      '업로드된 족보 파일을 다운로드하여 확인해 보니 실제 시험 문제와 전혀 다른 내용이 담겨 있었습니다. 다른 학교의 시험지를 가져다 올린 것으로 추정되며, 많은 학생들이 잘못된 족보를 공부 자료로 활용하고 있어 피해가 우려됩니다. 즉각적인 삭제와 업로더 조치를 요청합니다.',
    reportCause: 'EXAM_FALSE_REVIEW',
    target: '278',
    link: getInquiryTargetLink(20),
    group: 'REPORT',
    subGroup: 'EXAM_REVIEW_REPORT',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-04T08:40:15.222222',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
  21: {
    postId: 21,
    userRoleId: 2,
    isWriter: false,
    userId: 31313131,
    userDisplay: '안전댓글',
    title: '댓글에 욕설이 포함되어 있습니다',
    content:
      '게시글에 달린 댓글에 다른 사용자를 향한 심한 욕설과 비하 표현이 포함되어 있습니다. 해당 댓글은 커뮤니티 이용 정책에 명백히 위반되며, 이미 여러 사용자가 불쾌함을 표현하고 있습니다. 댓글 삭제 및 해당 사용자에 대한 경고 조치를 요청합니다.',
    reportCause: 'COMMENT_INSULT_OR_DEFAMATION',
    target: '502',
    link: getInquiryTargetLink(21),
    group: 'REPORT',
    subGroup: 'COMMENT_REPORT',
    status: 'PENDING',
    commentCount: 0,
    createdAt: '2026-04-03T20:17:31.444444',
    updatedAt: '2026-04-04T07:45:00.000000',
    isEdited: true,
    isWriterWithdrawn: false,
    attachments: [],
  },
  22: {
    postId: 22,
    userRoleId: 2,
    isWriter: false,
    userId: 32323232,
    userDisplay: '알림이',
    title: '공지 알림 수신 관련 문의',
    content:
      '앱 알림 설정에서 공지 알림을 활성화하였음에도 불구하고 최근 공지 사항에 대한 푸시 알림을 받지 못하고 있습니다. 다른 카테고리의 알림은 정상적으로 수신되는데 공지 알림만 오지 않습니다. 기기는 iOS 17을 사용하고 있으며, 앱 재설치 후에도 동일한 증상이 발생하고 있습니다.',
    reportCause: null,
    target: null,
    link: getInquiryTargetLink(22),
    group: 'INQUIRY',
    subGroup: 'NOTICE_INQUIRY',
    status: 'COMPLETED',
    commentCount: 1,
    createdAt: '2026-04-02T17:03:27.555555',
    updatedAt: null,
    isEdited: false,
    isWriterWithdrawn: false,
    attachments: [],
  },
};
