export const LECTURE_TYPE = {
  MAJOR_REQUIRED: 'MAJOR_REQUIRED',
  MAJOR_ELECTIVE: 'MAJOR_ELECTIVE',
  GENERAL_REQUIRED: 'GENERAL_REQUIRED',
  GENERAL_ELECTIVE: 'GENERAL_ELECTIVE',
  OTHER: 'OTHER',
} as const;

export const SEMESTER = {
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  SUMMER: 'SUMMER',
  WINTER: 'WINTER',
  OTHER: 'OTHER',
} as const;

export const EXAM_TYPE = {
  MIDTERM: 'MIDTERM',
  FINALTERM: 'FINALTERM',
} as const;

export const STATUS = {
  CONFIRMED: 'CONFIRMED',
  UNCONFIRMED: 'UNCONFIRMED',
} as const;
