export const EXAM_REVIEW_LIST_DUMMY = [
  {
    id: 1,
    status: 'CONFIRMED',
    reviewTitle: '수학 중간고사 후기 - 난이도 적절',
    courseName: '미적분학 I',
    professor: '김교수',
    semester: '2024-1',
    examType: '중간고사',
    examFormat: '객관식 20문항, 주관식 5문항',
    uploadTime: '2024-03-15 14:30',
    author: '김학생',
    discussion: '계산 실수 주의',
    manager: '이관리자',
  },
  {
    id: 2,
    status: 'CONFIRMED_WITH_MODIFICATION',
    reviewTitle: '영어 기말고사 후기 - 리스닝 어려움',
    courseName: '영어회화 II',
    professor: '박교수',
    semester: '2024-1',
    examType: '기말고사',
    examFormat: '리스닝 30문항, 작문 2문항',
    uploadTime: '2024-06-20 16:45',
    author: '이학생',
    discussion: '리스닝 속도 빠름',
    manager: '박관리자',
  },
  {
    id: 3,
    status: 'CONFIRMED',
    reviewTitle: '물리학 중간고사 후기 - 공식 암기 필수',
    courseName: '일반물리학 I',
    professor: '최교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '계산문제 15문항',
    uploadTime: '2024-09-10 10:20',
    author: '박학생',
    discussion: '공식 정리 중요',
    manager: '김관리자',
  },
  {
    id: 4,
    status: 'PUNISHMENT',
    reviewTitle: '국어 모의고사 후기',
    courseName: '현대문학의 이해',
    professor: '정교수',
    semester: '2024-2',
    examType: '모의고사',
    examFormat: '서술형 10문항',
    uploadTime: '2024-10-05 13:15',
    author: '최학생',
    discussion: '부적절한 내용 포함',
    manager: '이관리자',
  },
  {
    id: 5,
    status: 'DELETED',
    reviewTitle: '화학 기말고사 후기 - 실험 문제 다수',
    courseName: '유기화학 II',
    professor: '한교수',
    semester: '2024-2',
    examType: '기말고사',
    examFormat: '실험문제 8문항, 이론 12문항',
    uploadTime: '2024-12-15 09:30',
    author: '정학생',
    discussion: '실험 과정 숙지 필요',
    manager: '박관리자',
  },
  {
    id: 6,
    status: 'CONFIRMED',
    reviewTitle: '프로그래밍 중간고사 후기 - 코딩 문제 위주',
    courseName: '자료구조론',
    professor: '이교수',
    semester: '2024-1',
    examType: '중간고사',
    examFormat: '코딩 5문항, 이론 10문항',
    uploadTime: '2024-04-10 11:20',
    author: '박학생',
    discussion: '알고리즘 이해 필수',
    manager: '김관리자',
  },
  {
    id: 7,
    status: 'CONFIRMED_WITH_MODIFICATION',
    reviewTitle: '경제학 기말고사 후기 - 계산 문제 많음',
    courseName: '거시경제학',
    professor: '장교수',
    semester: '2024-1',
    examType: '기말고사',
    examFormat: '계산 15문항, 서술 5문항',
    uploadTime: '2024-06-25 15:30',
    author: '최학생',
    discussion: '공식 암기 중요',
    manager: '이관리자',
  },
  {
    id: 8,
    status: 'CONFIRMED',
    reviewTitle: '생물학 중간고사 후기 - 암기 위주',
    courseName: '일반생물학',
    professor: '윤교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '객관식 25문항',
    uploadTime: '2024-09-15 13:45',
    author: '김학생',
    discussion: '교과서 정독 필요',
    manager: '박관리자',
  },
  {
    id: 9,
    status: 'PUNISHMENT',
    reviewTitle: '철학 기말고사 후기',
    courseName: '서양철학사',
    professor: '조교수',
    semester: '2024-2',
    examType: '기말고사',
    examFormat: '논술 3문항',
    uploadTime: '2024-12-10 16:20',
    author: '이학생',
    discussion: '부적절한 표현 사용',
    manager: '김관리자',
  },
  {
    id: 10,
    status: 'DELETED',
    reviewTitle: '통계학 중간고사 후기 - 계산기 필수',
    courseName: '통계학개론',
    professor: '한교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '계산 20문항',
    uploadTime: '2024-10-20 09:15',
    author: '박학생',
    discussion: '공식 정리 필요',
    manager: '이관리자',
  },
  {
    id: 11,
    status: 'CONFIRMED',
    reviewTitle: '심리학 기말고사 후기 - 사례 분석 위주',
    courseName: '인지심리학',
    professor: '정교수',
    semester: '2024-1',
    examType: '기말고사',
    examFormat: '사례분석 10문항, 객관식 15문항',
    uploadTime: '2024-06-18 14:10',
    author: '최학생',
    discussion: '실제 사례 이해 중요',
    manager: '박관리자',
  },
  {
    id: 12,
    status: 'CONFIRMED_WITH_MODIFICATION',
    reviewTitle: '회계학 중간고사 후기 - 계산 실수 주의',
    courseName: '재무회계',
    professor: '김교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '계산 12문항, 이론 8문항',
    uploadTime: '2024-09-25 10:30',
    author: '김학생',
    discussion: '계산 과정 체크 필요',
    manager: '김관리자',
  },
  {
    id: 13,
    status: 'CONFIRMED',
    reviewTitle: '법학 기말고사 후기 - 판례 암기 필수',
    courseName: '민법총칙',
    professor: '박교수',
    semester: '2024-1',
    examType: '기말고사',
    examFormat: '사례 5문항, 단답 20문항',
    uploadTime: '2024-06-22 11:45',
    author: '이학생',
    discussion: '주요 판례 정리 필요',
    manager: '이관리자',
  },
  {
    id: 14,
    status: 'PUNISHMENT',
    reviewTitle: '사회학 중간고사 후기',
    courseName: '사회학개론',
    professor: '최교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '논술 4문항',
    uploadTime: '2024-10-08 15:20',
    author: '박학생',
    discussion: '개인 의견 과도하게 포함',
    manager: '박관리자',
  },
  {
    id: 15,
    status: 'DELETED',
    reviewTitle: '체육학 기말고사 후기 - 실기 평가 포함',
    courseName: '스포츠생리학',
    professor: '이교수',
    semester: '2024-2',
    examType: '기말고사',
    examFormat: '이론 15문항, 실기 평가',
    uploadTime: '2024-12-12 08:30',
    author: '최학생',
    discussion: '실기 준비 중요',
    manager: '김관리자',
  },
  {
    id: 16,
    status: 'CONFIRMED',
    reviewTitle: '음악학 중간고사 후기 - 청음 시험 어려움',
    courseName: '서양음악사',
    professor: '장교수',
    semester: '2024-1',
    examType: '중간고사',
    examFormat: '청음 10문항, 이론 15문항',
    uploadTime: '2024-04-12 13:20',
    author: '김학생',
    discussion: '청음 연습 필수',
    manager: '이관리자',
  },
  {
    id: 17,
    status: 'CONFIRMED_WITH_MODIFICATION',
    reviewTitle: '미술학 기말고사 후기 - 작품 분석 위주',
    courseName: '서양미술사',
    professor: '윤교수',
    semester: '2024-1',
    examType: '기말고사',
    examFormat: '작품분석 8문항, 객관식 12문항',
    uploadTime: '2024-06-28 16:40',
    author: '이학생',
    discussion: '작품 특징 정리 필요',
    manager: '박관리자',
  },
  {
    id: 18,
    status: 'CONFIRMED',
    reviewTitle: '건축학 중간고사 후기 - 설계 이론 중심',
    courseName: '건축설계론',
    professor: '조교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '설계 3문항, 이론 17문항',
    uploadTime: '2024-09-30 12:15',
    author: '박학생',
    discussion: '설계 원리 이해 중요',
    manager: '김관리자',
  },
  {
    id: 19,
    status: 'PUNISHMENT',
    reviewTitle: '언어학 기말고사 후기',
    courseName: '언어학개론',
    professor: '한교수',
    semester: '2024-2',
    examType: '기말고사',
    examFormat: '분석 10문항, 이론 10문항',
    uploadTime: '2024-12-08 14:50',
    author: '최학생',
    discussion: '부정확한 정보 포함',
    manager: '이관리자',
  },
  {
    id: 20,
    status: 'DELETED',
    reviewTitle: '환경학 중간고사 후기 - 현장 사례 다수',
    courseName: '환경과학',
    professor: '정교수',
    semester: '2024-2',
    examType: '중간고사',
    examFormat: '사례분석 12문항, 계산 8문항',
    uploadTime: '2024-10-15 11:30',
    author: '김학생',
    discussion: '환경 이슈 정리 필요',
    manager: '박관리자',
  },
];

// 상태 리스트
export const STATUS_COLOR = [
  { id: 1, code: 'CONFIRMED', name: '확인완료', color: 'bg-blue-500' },
  {
    id: 2,
    code: 'CONFIRMED_WITH_MODIFICATION',
    name: '수정+확인완료',
    color: 'bg-green-500',
  },
  { id: 3, code: 'NEED_DISCUSSION', name: '논의필요', color: 'bg-orange-500' },
  { id: 4, code: 'PUNISHMENT', name: '징계', color: 'bg-red-500' },
  { id: 5, code: 'DELETED', name: '삭제된 족보', color: 'bg-gray-300' },
  { id: 6, code: 'UNCONFIRMED', name: '미확인 족보', color: 'bg-gray-900' },
];

// 수강 학기
export const SEMESTER_LIST = [
  '2025-1',
  '2025-여름',
  '2025-2',
  '2025-겨울',
  '2024-1',
  '2024-여름',
  '2024-2',
  '2024-겨울',
  '2023-1',
  '2023-여름',
  '2023-2',
  '2023-겨울',
  '2022-1',
  '2022-여름',
  '2022-2',
  '2022-겨울',
  '2021-1',
  '2021-여름',
  '2021-2',
  '2021-겨울',
  '2020-1',
  '2020-여름',
  '2020-2',
  '2020-겨울',
];

// 시험 종류 리스트
export const EXAM_TYPE_LIST = ['중간고사', '기말고사'];

// 담당자 리스트
export const MANAGER_LIST = [
  '김준희',
  '류미성',
  '장아현',
  '송희원',
  '김선진',
  '정민주',
  '양하은',
  '윤현서',
  '이지은',
  '박영희',
  '최영민',
  '정영희',
  '김영희',
  '이영희',
  '박영희',
  '최영희',
];
