name: 🧹 Chore Request
description: 프로젝트 관리와 관련된 작업을 요청합니다.
title: '[CHORE] '
labels: ['🧹 Chore']
body:
  - type: textarea
    id: background
    attributes:
      label: 📌 배경
      description: 어떤 맥락에서 이 작업이 필요한지 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 📝 작업 내용
      description: 수행할 구체적인 작업 항목을 나열해주세요.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: 📋 추가 정보
      description: 추가로 공유할 내용이 있다면 자유롭게 작성해 주세요.
    validations:
      required: false
