export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  POSTS: '/posts',
  POST_COMMENTS: '/posts/comments',
  MEMBER_INFO: '/member/info',
  MEMBER_PENALTY: '/member/penalty',
  REVIEW_EXAM: '/reviews/exam',
  POINT_HISTORY: '/point/history',
  POINT_SINGLE: '/point/single',
  POINT_ALL: '/point/all',
  POINT_FREEZE: '/point/freeze',
  ALERTS: '/alerts',
  INQUIRY: '/inquiry',
  INQUIRY_FAQ: '/inquiry/faq',
} as const;
