export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  POST_COMMENTS: '/posts/comments',
  POST_MANAGE: '/posts/manage',
  POST_DETAIL: '/posts/manage/:postId',
  MEMBER_INFO: '/member/info',
  MEMBER_PENALTY: '/member/penalty',
  REVIEW_EXAM: '/reviews/exam',
  REVIEW_EXAM_PERIOD: '/reviews/exam-period',
  POINT_HISTORY: '/point/history',
  POINT_SINGLE: '/point/single',
  POINT_ALL: '/point/all',
  POINT_FREEZE: '/point/freeze',
  POINT_UPLOAD_EXCEL: '/point/excel-upload',
  INQUIRY_REPORT: '/report/inquiry',
  ALERTS: '/alerts',
} as const;
