export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  POST_TRASH: '/posts/trash',
  POST_COMMENTS: '/posts/comments',
  MEMBER_INFO: '/member/info',
  MEMBER_PENALTY: '/member/penalty',
  REVIEW_EXAM: '/reviews/exam',
  POINT_HISTORY: '/point/history',
  POINT_SINGLE: '/point/single',
  POINT_ALL: '/point/all',
  POINT_FREEZE: '/point/freeze',
  POINT_UPLOAD_EXCEL: '/point/excel-upload',
  ALERTS: '/alerts',
} as const;
