export { default as CommentPage } from './CommentPage';
export { default as ExamReviewPage } from './ExamReviewPage';
export { default as MemberInfoPage } from './MemberInfoPage';
export { default as PointSinglePage } from './points/PointSinglePage';
export { default as PointMultiplePage } from './points/PointMultiplePage';
export { default as PointAllPage } from './points/PointAllPage';
export { default as LogInPage } from './LogInPage';
export { default as PostPage } from './PostPage';
export { default as PushNotificationPage } from './PushNotificationPage';
